//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IStockMarket")]
    public interface IStockMarket {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockMarket/getStockValue", ReplyAction="http://tempuri.org/IStockMarket/getStockValueResponse")]
        double getStockValue(string strSymbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockMarket/getStockValue", ReplyAction="http://tempuri.org/IStockMarket/getStockValueResponse")]
        System.Threading.Tasks.Task<double> getStockValueAsync(string strSymbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockMarket/setStockValue", ReplyAction="http://tempuri.org/IStockMarket/setStockValueResponse")]
        double setStockValue(string strSymbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockMarket/setStockValue", ReplyAction="http://tempuri.org/IStockMarket/setStockValueResponse")]
        System.Threading.Tasks.Task<double> setStockValueAsync(string strSymbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockMarket/putStockValue", ReplyAction="http://tempuri.org/IStockMarket/putStockValueResponse")]
        double putStockValue(string strSymbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockMarket/putStockValue", ReplyAction="http://tempuri.org/IStockMarket/putStockValueResponse")]
        System.Threading.Tasks.Task<double> putStockValueAsync(string strSymbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockMarket/dumpStockValue", ReplyAction="http://tempuri.org/IStockMarket/dumpStockValueResponse")]
        double dumpStockValue(string strSymbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockMarket/dumpStockValue", ReplyAction="http://tempuri.org/IStockMarket/dumpStockValueResponse")]
        System.Threading.Tasks.Task<double> dumpStockValueAsync(string strSymbol);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockMarketChannel : Client.ServiceReference1.IStockMarket, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockMarketClient : System.ServiceModel.ClientBase<Client.ServiceReference1.IStockMarket>, Client.ServiceReference1.IStockMarket {
        
        public StockMarketClient() {
        }
        
        public StockMarketClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockMarketClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockMarketClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockMarketClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double getStockValue(string strSymbol) {
            return base.Channel.getStockValue(strSymbol);
        }
        
        public System.Threading.Tasks.Task<double> getStockValueAsync(string strSymbol) {
            return base.Channel.getStockValueAsync(strSymbol);
        }
        
        public double setStockValue(string strSymbol) {
            return base.Channel.setStockValue(strSymbol);
        }
        
        public System.Threading.Tasks.Task<double> setStockValueAsync(string strSymbol) {
            return base.Channel.setStockValueAsync(strSymbol);
        }
        
        public double putStockValue(string strSymbol) {
            return base.Channel.putStockValue(strSymbol);
        }
        
        public System.Threading.Tasks.Task<double> putStockValueAsync(string strSymbol) {
            return base.Channel.putStockValueAsync(strSymbol);
        }
        
        public double dumpStockValue(string strSymbol) {
            return base.Channel.dumpStockValue(strSymbol);
        }
        
        public System.Threading.Tasks.Task<double> dumpStockValueAsync(string strSymbol) {
            return base.Channel.dumpStockValueAsync(strSymbol);
        }
    }
}
